name: Super-Linter

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # VERY IMPORTANT – turn off everything
          VALIDATE_ALL_CODEBASE: false

          # ONLY ENABLE THESE TWO
          VALIDATE_YAML: true
          VALIDATE_GITHUB_ACTIONS: true
