name: Super-Linter

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         
          clean: true              
          ref: ${{ github.head_ref }} 

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Disable all linters by default
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_ARM: false
          VALIDATE_BASH: false
          VALIDATE_CLOJURE: false
          VALIDATE_COFFEESCRIPT: false
          VALIDATE_CSHARP: false
          VALIDATE_CSS: false
          VALIDATE_DART: false
          VALIDATE_DOCKER: false
          VALIDATE_ENV: false
          VALIDATE_GITLEAKS: false
          VALIDATE_GO: false
          VALIDATE_GROOVY: false
          VALIDATE_HTML: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JAVA: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_KUBERNETES: false
          VALIDATE_LATEX: false
          VALIDATE_LUA: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PROTOBUF: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_R: false
          VALIDATE_RAKU: false
          VALIDATE_RUST: false
          VALIDATE_SCALAFMT: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_SQL: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TS_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
